extends: eslint:recommended
parserOptions:
    sourceType: module
env:
    node: true
    es6: true
rules:
    no-console:
      - warn
    no-unused-vars:
      - warn
    quotes:
      - error
      - single
      - "avoid-escape"
